version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./reader
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    restart: unless-stopped